import os
import sys
import csv
import json
import glob
import shutil
from datetime import datetime

def _bootstrap_find_research_root(script_file):
    current = os.path.dirname(os.path.abspath(script_file))
    while os.path.basename(current) != "Research":
        parent = os.path.dirname(current)
        if parent == current:
            print(f"\n[FATAL ERROR] Could not locate a 'Research' anchor folder above: {script_file}")
            sys.exit(1)
        current = parent
    return current

_PROJECT_ROOT = _bootstrap_find_research_root(__file__)
_COMMON_DIR = os.path.join(_PROJECT_ROOT, "Phase 1", "_common")
if _COMMON_DIR not in sys.path:
    sys.path.insert(0, _COMMON_DIR)
_STEPD_DIR = os.path.dirname(os.path.abspath(__file__))
if _STEPD_DIR not in sys.path:
    sys.path.insert(0, _STEPD_DIR)

import phase1_common as common

# =============================================================================
# PHASE 1De FOLD INGEST -- take AlphaFold Server downloads into the pipeline,
# and gate them on confidence BEFORE anything is scored.
#
# WHY THE GATE EXISTS. Deviation #21 is the record of what happens without it:
# the construct passed MolProbity with an EXCELLENT score while AlphaFold said
# its fold was undetermined, because Step 2B kept only model_0 and discarded
# every confidence file, so nothing downstream could see the problem for a
# whole phase. SEMA-3D is a structure-based predictor -- a low-confidence fold
# yields confident-LOOKING epitope patches that mean nothing. So this step
# archives every FILE in the download -- all five ranked models, all summary
# confidences, the per-atom full_data and the job request -- and reports, per
# antigen:
#
# (It deliberately does not recurse into the job's msas/ and templates/
# subdirectories: those are intermediate search output, regenerated by re-
# running the job, and the project already excludes AlphaFold MSAs from version
# control for size. The RESULTS are archived; the search scratch is not.)
#
#   - global pTM, and its spread across the five ranked models
#   - mean per-residue pLDDT
#   - pLDDT AT EACH B-CELL EPITOPE WINDOW, which is what actually matters here
#
# That last one is the point. pTM is a GLOBAL score and is dragged down by
# membrane anchors and disordered tails that no B-cell epitope in this
# construct occupies. An antigen can have poor pTM and a perfectly well
# determined ectodomain. Judging SEMA input on pTM alone would throw away good
# data; judging it on nothing would repeat deviation #21.
#
# Matching is by SEQUENCE, not by folder name: each job_request.json is
# compared against the subunit FASTAs Phase1De_foldPrep.py emitted, so a
# mislabelled or re-run job cannot be silently attached to the wrong antigen.
# =============================================================================

# AlphaFold's own confidence bands, as used in Step 2C and deviation #21.
PLDDT_CONFIDENT = 70.0
PTM_GLOBAL_FOLD = 0.50


def _submission_sequences():
    sub = os.path.join(_PROJECT_ROOT, "Step_Outputs", "Phase1", "Phase1D",
                       "Phase1De", "Folds", "_submissions")
    out = {}
    if not os.path.isdir(sub):
        return out
    for f in os.listdir(sub):
        if f.endswith("_subunit.fasta"):
            target = f.replace("_subunit.fasta", "")
            with open(os.path.join(sub, f)) as fh:
                out[target] = "".join(l.strip() for l in fh if not l.startswith(">")).upper()
    return out


def _job_sequence(job_dir):
    reqs = glob.glob(os.path.join(job_dir, "*_job_request.json"))
    if not reqs:
        return None
    data = json.load(open(reqs[0]))
    entry = data[0] if isinstance(data, list) else data
    for s in entry.get("sequences", []):
        if "proteinChain" in s:
            return s["proteinChain"]["sequence"].upper()
    return None


def _per_residue_plddt(cif_path):
    """
    AlphaFold writes per-atom pLDDT into the B-factor column. Averaged per
    residue, which is how AlphaFold's own viewer reports it.

    Column positions are read from the _atom_site loop header rather than
    assumed. Hardcoded indices are what broke the first version of this
    function: the residue number was taken from a column that holds the chain
    id, every parse raised, and the step cheerfully reported "0 residues
    modelled" for structures that were completely fine.
    """
    cols = {}
    sums, counts, order = {}, {}, []
    in_loop = False
    with open(cif_path) as fh:
        for line in fh:
            if line.startswith("_atom_site."):
                cols[line.strip().split(".", 1)[1]] = len(cols)
                in_loop = True
                continue
            if in_loop and line.startswith(("ATOM", "HETATM")):
                parts = line.split()
                try:
                    bfac = float(parts[cols["B_iso_or_equiv"]])
                    resi = int(parts[cols["label_seq_id"]])
                except (ValueError, IndexError, KeyError):
                    continue
                if resi not in sums:
                    sums[resi], counts[resi] = 0.0, 0
                    order.append(resi)
                sums[resi] += bfac
                counts[resi] += 1
            elif in_loop and line.startswith("#"):
                in_loop = False
    return [sums[r] / counts[r] for r in sorted(order)]


def _bcell_epitopes_by_target():
    """
    B-cell epitopes in the construct, keyed by the target whose SUBUNIT they
    actually sit in -- not by the Target label.

    Keying on the label would be wrong here for the reason deviation #26
    records: 9 of the 14 HIV epitopes carry a label from the Entrez query that
    fetched their parent polyprotein rather than from the protein they lie in.
    Looking up LTVWGIKQLQARVLAV under "HIV_gp120" finds nothing, because it is
    a gp41 epitope. Each peptide is therefore located by sequence search across
    every subunit reference, so its pLDDT is read from the fold it belongs to.
    """
    folder = os.path.join(_PROJECT_ROOT, "Step_Outputs", "Phase1", "Phase1G")
    latest = common.latest_file(folder, suffix=".csv")
    if latest is None:
        return {}
    with open(latest) as f:
        row = next(csv.DictReader(f))
    classes = {}
    for seg in row["Boundary_Map"].split(";"):
        seg = seg.strip()
        if seg.startswith("B-cell:"):
            classes[seg[len("B-cell:"):].split("[")[0]] = True
    subs = _submission_sequences()
    out = {}
    for item in row["Epitope_Provenance"].split(";"):
        if ":" not in item:
            continue
        pep, label = item.rsplit(":", 1)
        pep, label = pep.strip(), label.strip()
        if pep not in classes:
            continue
        owners = [t for t, ref in subs.items() if pep in ref]
        if not owners:
            # Selected from a non-Var_01 variant; the subunit references are
            # Var_01-derived, so fall back to the label and say so downstream.
            out.setdefault(label, []).append(pep)
            continue
        for t in owners:
            out.setdefault(t, []).append(pep)
    return out


def run_fold_ingest(source_dir):
    common.print_banner("PHASE 1De FOLD INGEST: ALPHAFOLD MODELS + CONFIDENCE GATE")

    subs = _submission_sequences()
    if not subs:
        print("[ERROR] No submission FASTAs found. Run Phase1De_foldPrep.py first.")
        return

    folds_root = os.path.join(_PROJECT_ROOT, "Step_Outputs", "Phase1", "Phase1D",
                              "Phase1De", "Folds")
    bcell = _bcell_epitopes_by_target()

    job_dirs = [d for d in glob.glob(os.path.join(source_dir, "*", "*")) if os.path.isdir(d)]
    job_dirs += [d for d in glob.glob(os.path.join(source_dir, "*")) if os.path.isdir(d)
                 and glob.glob(os.path.join(d, "*_job_request.json"))]

    rows = []
    matched = {}
    for job in sorted(set(job_dirs)):
        seq = _job_sequence(job)
        if seq is None:
            continue
        hits = [t for t, s in subs.items() if s == seq]
        if not hits:
            print(f"[WARNING] {os.path.basename(job)}: sequence matches no submission -- skipped.")
            continue
        matched[hits[0]] = job

    print(f"[INFO] Matched {len(matched)}/{len(subs)} antigens by exact sequence.\n")

    for target in sorted(subs):
        job = matched.get(target)
        if job is None:
            print(f"[WARNING] {target}: no AlphaFold job found.")
            continue

        dest = os.path.join(folds_root, target)
        os.makedirs(dest, exist_ok=True)
        # Archive the FULL download -- deviation #21's lesson.
        for src in glob.glob(os.path.join(job, "*")):
            if os.path.isfile(src):
                shutil.copy2(src, os.path.join(dest, os.path.basename(src)))

        name = os.path.basename(job).replace("fold_", "")
        ptms = []
        for i in range(5):
            f = os.path.join(job, f"fold_{name}_summary_confidences_{i}.json")
            if os.path.isfile(f):
                ptms.append(json.load(open(f)).get("ptm"))
        model0 = os.path.join(dest, f"fold_{name}_model_0.cif")
        plddt = _per_residue_plddt(model0) if os.path.isfile(model0) else []
        mean_plddt = sum(plddt) / len(plddt) if plddt else 0.0
        pct_conf = 100.0 * sum(1 for p in plddt if p >= PLDDT_CONFIDENT) / len(plddt) if plddt else 0.0

        ref = subs[target]
        print(f"  {target}")
        print(f"    pTM {ptms[0] if ptms else '?'} (5 models: {ptms})"
              f"{'  <-- BELOW 0.50 global-fold line' if ptms and ptms[0] < PTM_GLOBAL_FOLD else ''}")
        print(f"    mean pLDDT {mean_plddt:5.1f} | residues >=70: {pct_conf:5.1f}% "
              f"| modelled {len(plddt)}/{len(ref)}")

        ep_rows = []
        for pep in bcell.get(target, []):
            start = ref.find(pep)
            if start == -1:
                ep_rows.append((pep, None, "not in this subunit"))
                continue
            win = plddt[start:start + len(pep)]
            if not win:
                ep_rows.append((pep, None, "not modelled"))
                continue
            m = sum(win) / len(win)
            verdict = "CONFIDENT" if m >= PLDDT_CONFIDENT else "LOW CONFIDENCE"
            ep_rows.append((pep, m, verdict))
        for pep, m, verdict in ep_rows:
            shown = f"{m:5.1f}" if m is not None else "    -"
            print(f"      B-cell {pep:<18} pLDDT {shown}  {verdict}")
        if not ep_rows:
            print(f"      (no B-cell epitope labelled to this target)")

        rows.append({"Target": target, "Job": os.path.basename(job),
                     "pTM_model0": ptms[0] if ptms else "",
                     "pTM_all": ";".join(str(p) for p in ptms),
                     "Mean_pLDDT": round(mean_plddt, 1),
                     "Pct_Residues_pLDDT_ge70": round(pct_conf, 1),
                     "Modelled_Residues": len(plddt), "Reference_Length": len(ref),
                     "Global_Fold_Verdict": ("DETERMINED" if ptms and ptms[0] >= PTM_GLOBAL_FOLD
                                             else "UNDETERMINED"),
                     "BCell_Epitope_pLDDT": ";".join(
                         f"{p}:{'' if m is None else round(m,1)}" for p, m, _v in ep_rows)})

    out_dir = os.path.join(folds_root, "_confidence")
    os.makedirs(out_dir, exist_ok=True)
    ts = datetime.now().strftime("%Y-%m-%d_%H%M")
    out_path = os.path.join(out_dir, f"Phase1De_FoldConfidence_{ts}.csv")
    if rows:
        with open(out_path, "w", newline="") as f:
            w = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
            w.writeheader()
            w.writerows(rows)
        print(f"\n[INFO] Confidence report: {out_path}")
    print(f"[INFO] Models archived under: {folds_root}/<TARGET>/")
    print("=" * 90 + "\n")


if __name__ == "__main__":
    src = sys.argv[1] if len(sys.argv) > 1 else "/Volumes/Extended SSD/Research/AlphaFold Results"
    run_fold_ingest(src)
